config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :posts

  get 'blog' => 'welcome#all', as: "blog"

  get 'about' => 'welcome#about', as: "about"

  get 'contact' => 'welcome#contact', as: "contact"

  get 'welcome' => 'welcome#post', as: "post_"

  get 'application' => 'welcome#application'

  get 'post/(:id)' => 'posts#views', as: "single"

  get 'posts/new/:id/delete' => 'posts#destroy', as: "delete"

  get 'posts/new/(:id)/edit' => 'posts#edit', as: "edit"

  get 'home' => 'posts#all', as: "home"

  get 'error' => 'posts#all', as: "error"

end

app/models/post.rb
class Post < ActiveRecord::Base
  post = Post.new(:title => "")
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  def index
    @post = Post.all
    render template: "post/post"
  end

  def show
    @post = Post.find(params[:id])
    render template: "post/post"
    @post.author_id = @post.author_id + 1
    @post.save
  end

  def new
    @posts = Post.all
    @post = Post.new
    @post.author_id = 1
    render template: "post/new"
  end

  def create
    @posts = Post.all
    @url3 = request.original_url
    if @url3.split('/')[-1] != "new?fname=BroccoliCasserole"
    @post = Post.new(post_params)
    @post.author_id = 1
    @post.save
    render template: "post/all"
  else
    redirect_to error_path
  end
  end

  def edit
    @post = Post.all
    @url = request.original_url
    @post = Post.find(params[:id])
    if @url.split('/')[-1] == "edit?fname1=BroccoliCasserole"
    render template: "post/new"
    @post.save
    else
    redirect_to error_path
  end
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post
    else
      render template: "post/new"
    end
    @post.save
  end

  def destroy
    @url1 = request.original_url
    @post = Post.find(params[:id])
    if @url1.split('/')[-1] == "delete?fname=BroccoliCasserole"
    @post.destroy
    Post.all
    redirect_to home_path
    @post.save
  else
    redirect_to error_path
  end
  end
  def all
    @posts = Post.all
    render template: "post/all"
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @posts = Post.all
    render template: "layouts/index.html.erb"
  end

  def about
    render template: "layouts/about.html.erb"
  end

  def contact
    render template: "layouts/contact.html.erb"
  end

  def post
    render template: "layouts/post.html.erb"
  end

  def application
    render template: "layouts/application.html.erb"
  end

  def show
    @post = Post.find(params[:id])
    render template: "post/post"
    @post.save
  end

  def new
    @post = Post.new
    render template: "post/new"
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to home_path
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
    render template: "post/new"
    @post.save
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post
    else
      render template: "post/new"
    end
    @post.save
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    Post.all
    redirect_to home_path
    @post.save
  end
  def all
    @posts = Post.all
    render template: "post/all"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/about.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Seabrook Barnett</title>

    <!-- Bootstrap Core CSS -->

    <%= stylesheet_link_tag "bootstrap.min.css" %>
    <%= stylesheet_link_tag "bootstrap.css" %>
    <%= stylesheet_link_tag "clean-blog.min.css" %>
    <%= stylesheet_link_tag "clean-blog.css" %>
    <!-- Custom CSS -->

    <!-- Custom Fonts -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="http://www.UniversallyThinking.com/">Main Site</a><a class="navbar-brand" href="http://univthink.com/">Think Tank</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                  <li>
                      <a href="<%= root_path %>">Home</a>
                  </li>
                  <li>
                      <a href="<%= about_path %>">About</a>
                  </li>
                  <li>
                      <a href="<%= blog_path %>">Blog</a>
                  </li>
                  <li>
                      <a href="<%= contact_path %>">Contact</a>
                  </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url('<%= asset_path 'about-bg.jpg' %>')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="page-heading">
                        <h1>About Me</h1>
                        <hr class="small">
                        <span class="subheading">This is what I do.</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostrum molestiae debitis nobis, quod sapiente qui voluptatum, placeat magni repudiandae accusantium fugit quas labore non rerum possimus, corrupti enim modi! Et.</p>
            </div>
        </div>
    </div>

    <hr>

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; Seabrook Barnett 2015</p>
                </div>
            </div>
        </div>
    </footer>

    <%= javascript_include_tag "application.js" %>

</body>

</html>

app/views/layouts/contact.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Seabrook Barnett - Contact</title>

    <!-- Bootstrap Core CSS -->
    <%= stylesheet_link_tag "bootstrap.min.css" %>
    <%= stylesheet_link_tag "bootstrap.css" %>
    <%= stylesheet_link_tag "clean-blog.min.css" %>
    <%= stylesheet_link_tag "clean-blog.css" %>

    <!-- Custom Fonts -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="http://www.UniversallyThinking.com/">Main Site</a><a class="navbar-brand" href="http://univthink.com/">Think Tank</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                  <li>
                      <a href="<%= root_path %>">Home</a>
                  </li>
                  <li>
                      <a href="<%= about_path %>">About</a>
                  </li>
                  <li>
                      <a href="<%= blog_path %>">Blog</a>
                  </li>
                  <li>
                      <a href="<%= contact_path %>">Contact</a>
                  </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url('<%= asset_path 'contact-bg.png' %>')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="page-heading">
                        <h1>Contact Me</h1>
                        <hr class="small">
                        <span class="subheading">Have questions? I have answers (maybe).</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <p>Want to get in touch with me? Fill out the form below to send me a message and I will try to get back to you within 24 hours!</p>
                <!-- Contact Form - Enter your email address on line 19 of the mail/contact_me.php file to make this form work. -->
                <!-- WARNING: Some web hosts do not allow emails to be sent through forms to common mail hosts like Gmail or Yahoo. It's recommended that you use a private domain email address! -->
                <!-- NOTE: To use the contact form, your site must be on a live web host with PHP! The form will not work locally! -->
                <div name="sentMessage" id="contactForm" novalidate>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <h3>Name</h3>
                            <h1 style="font-weight: normal;">Benjamin Seabrook Barnett</h1>
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <h3>Email Address</h3>
                            <h1 style="font-weight: normal;"><a href="mailto:benjamin@universallythinking.com" style="text-decoration: none;" target="_top">benjamin@UniversallyThinking.com</a></h1>
                            <p class="help-block text-danger"></h>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <h3>Phone Number</h3>
                            <h1 style="font-weight: normal;">1(513)545-3118</h1>
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <br>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <hr>

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; Seabrook Barnett 2015</p>
                </div>
            </div>
        </div>
    </footer>

    <%= javascript_include_tag "application.js" %>


</body>

</html>

app/views/layouts/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <script>
    function validateForm() {
      if (document.myForm.fname.value != null)
      {
        window.location = "<%= $secret_url %> + "/" + document.myForm.fname.value";
        return true;
      }
      else
      {
        alert("Name must be filled out");
        return false;
      }
}
    </script>
    <script>
    <!--
    function validateForm1() {
        if (document.myForm1.fname1.value != null)
        {
          window.location = "<%= $secret_url1 %> + "/" + document.myForm1.fname.value";
          return true;
        }
        else
        {
          alert("Password must be filled out");
          return false;
        }
} //-->
    </script>
    <title>Seabrook Barnett</title>

    <%= stylesheet_link_tag "bootstrap.min.css" %>
    <%= stylesheet_link_tag "bootstrap.css" %>
    <%= stylesheet_link_tag "clean-blog.min.css" %>
    <%= stylesheet_link_tag "clean-blog.css" %>

    <!-- Custom Fonts -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="http://www.UniversallyThinking.com/">Main Site</a><a class="navbar-brand" href="http://univthink.com/">Think Tank</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="<%= root_path %>">Home</a>
                    </li>
                    <li>
                        <a href="<%= about_path %>">About</a>
                    </li>
                    <li>
                        <a href="<%= blog_path %>">Blog</a>
                    </li>
                    <li>
                        <a href="<%= contact_path %>">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url('<%= asset_path 'home-bg.jpg' %>')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>Seabrook (Ben) Barnett</h1>
                        <hr class="small">
                        <span class="subheading">A Simple Blog Built on Bootstrap/Rails</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
              <% @posts.each do |p| %>


              <div class="post-preview">
                  <h2 class="post-title"><%= link_to p.title, "posts" + "/#{p.id}" %></h2>
                        <h3 class="post-body" style="font-weight: normal;">
                          <%=raw sanitize(simple_format(p.body), :tags => %w(br p) ) %>
                        </h3>                        </h3>

                    <p class="post-meta">Posted on <%= p.created_at %></p>
                    <p class="post-meta">This post has been viewed <a href="#"><%= p.author_id %></a> times.</p>

              </div>
              <% $secret_url = new_post_path + "/#{(p.id.to_s)}" + "/delete" %>
              <% $secret_url1 = new_post_path + "/#{(p.id.to_s)}" + "/edit" %>
          <h6><form name="myForm" onsubmit="return validateForm()" action="<%= $secret_url %>" method="get">
Password: <input type="password" name="fname">
<input type="submit" value="DELETE">
</form></h6>

<h6><form name="myForm1" onsubmit="return validateForm1()" action="<%= $secret_url1 %>" method="get">

Password: <input type="password" name="fname1">
<input type="submit" value="EDIT">
</form></h6>
          <% end %>
                <hr>
                <!-- Pager -->
                <ul class="pager">
                    <li class="next">
                        <a href="#">Older Posts &rarr;</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <hr>

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="http://twitter.com/univthink">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="https://www.facebook.com/UniversallyThinking/">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="http://github.com/univthink/">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; Seabrook Barnett 2015</p>
                </div>
            </div>
        </div>
    </footer>
    <%= javascript_include_tag "application.js" %>

</body>

</html>